max_width = 100
hard_tabs = false
tab_spaces = 4
newline_style = "Auto"
reorder_imports = true
reorder_modules = true
remove_nested_parens = true
edition = "2021"
merge_derives = true
force_explicit_abi = true
imports_granularity = "Crate"
